networks:
  default-net:
    name: default-net
    driver: bridge

services:
  kafka:
    image: bitnami/kafka:3.8
    container_name: kafka
    restart: unless-stopped
    networks:
      - default-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_KRAFT_CLUSTER_ID: 9
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: slideshow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    networks:
      - default-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  slideshow:
    build:
      context: .
    image: "jyliana/slideshow:v1"
    container_name: slideshow_service
    depends_on:
      - postgres
      - kafka
    ports:
      - "8012:8012"
    networks:
      - default-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/slideshow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

volumes:
  kafka_data:
    driver: local
  postgres_data: