server:
  port: 8012

spring:
  application:
    name: Slide show
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/slideshow
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
